.TH SHELL 1 "April 2024" "Version 1.0" "Shell User Manual"
.SH NAME
shell \- simulate a shell that accepts DOS commands and displays Linux command output
.SH SYNOPSIS
.B shell
.SH DESCRIPTION
.B shell
simulates a shell environment that accepts DOS commands
and translates them into equivalent Linux commands, executing them and
displaying the output (results) to the user.
.SH OPTIONS
No command line options are available.
.SH USAGE
Upon launching \fBshell\fR, users can input DOS commands, and the
shell will translate these commands into corresponding Linux commands and
execute them. The output of the executed Linux commands will be displayed
to the user.
.PP
Users are required to provide a text file for mapping between DOS and Linux
commands. Each line of the text file should contain a DOS command followed
by its equivalent Linux command. The shell will reference this file for
command translation.
.SH EXAMPLES
Suppose the mapping file contains the following entries:
.nf
.B dir    ls
.B cls    clear
.fi
.PP
If the user enters "dir" into the \fBshell\fR, the shell will execute
"ls" command in Linux and display the directory listing.
.PP
If the user enters "cls" into the \fBshell\fR, the shell will execute
"clear" command in Linux, clearing the screen.
.SH FILES
Mapping file: A text file containing mappings between DOS and Linux commands.

